apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-secret
  namespace: demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: app-secret

  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: prod/database
      property: DB_PASSWORD
      